### ISSUE TITLE
Problem with Scoreboard

### ISSUE THREAD

**Issue by TheIronMinerLv** [SubSide/KOTH#10]
Hello!

There is a problem with Featherboard support - I set up featherboard for koth correctly (named it as koth), it showed up and disappeared after the scheduled event finished. I have main scoreboard, which showed up after that event, but when I relogged, the koth scoreboard with empty variables again was visible... I tried to reload featherboard, that changed the board, but when I relogged, again I saw koth scoreboard... I negated permission for that koth scoreboard, tried many featherboard permissions, but nothing worked...

I'm using newest version of this KoTH plugin and newest 1.8.8 PaperSpigot.

**Comment by SubSide** [comment]
You sure you set it up correctly? Make sure to disable the default scoreboard from KoTH.

Last thing is to try a restart, a lot of problems with Featherboard get solved by restaeting a server

**Comment by TheIronMinerLv** [comment]
I'll try to disable default scoreboard, maybe that will fix it.

And I reatarted many times server, ofcourse after restart everything worked, but thats not the solution...

**Comment by SubSide** [comment]
Try following this: https://www.youtube.com/watch?v=3SuV36ne5KA

**Comment by TheIronMinerLv** [comment]
Still doesn't work, I made a video (ignore the language)

Here is the error, when I stop koth manually: http://pastebin.com/LtiNiKnj

And the video: https://youtu.be/NO9HPmTeNXI (wait a bit so youtube can process it to 720p)

**Comment by TheIronMinerLv** [comment]
Bump?

**Comment by SubSide** [comment]
Did you by any chance use the events in the Featherboard event file?
![8b7598f1e7634e159764c245018af828](https://cloud.githubusercontent.com/assets/4353101/18200712/723d9fd8-7106-11e6-995f-4c21773c60e1.png)

**Comment by TheIronMinerLv** [comment]
No, I wasn't used that file. I'll try to use that.

**Comment by TheIronMinerLv** [comment]
Then what shoud I do?

**Comment by SubSide** [comment]
Add me on Skype and I'll check it out

**Comment by TheIronMinerLv** [comment]
What's your skype nickname?

**Comment by SubSide** [comment]
Sorry for reacting so late, my Skype is "subside." without quotation marks
